server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tender_hack}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jdbc:
    template:
      max-rows: 10000
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info

yandex:
  cloud:
    bucket: hackathon-perm-2026
    access-key-id: ${YC_ACCESS_KEY_ID}
    secret-access-key: ${YC_SECRET_ACCESS_KEY}

ml:
  api:
    url: https://beerbears.website/api/ml
